homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    methods: GET
    defaults:
        route: users

login:
    path: /login
    controller: App\Controller\LoginController
    methods: GET|POST

delete_user:
    path: /users/delete
    controller: App\Controller\UserController::deleteUser
    methods: POST

users:
    path: /users/{id}
    controller: App\Controller\UserController::users
    methods: GET|POST
    defaults:
        id: null
