homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    methods: GET
    defaults:
        route: users

login:
    path: /login
    controller: App\Controller\LoginController
    methods: GET|POST

users:
    path: /users/{id}
    controller: App\Controller\UserController
    methods: GET|POST
    defaults:
        id: null
